- android/TodokTodok/app/build.gradle.kts
- android/TodokTodok/build.gradle.kts
- android/TodokTodok/gradle/libs.versions.toml
close #3 
+ 원활한 작업을 위해 버전 카탈로그에 있는 라이브러리 Depedency들을 항목별로 분류했습니다.
+ 추후 라이브러리를 추가할 때 어려우시다면 언제든 말씀해주세용 ☺️
+ 테스트 라이브러리는 미션에서 쓰던걸 그대로 옮겨왔습니다 !
---
- 2025.7.16. 17:00
---
<details>
- ❌ …
> #1 버전 카탈로그 정리 및 의존성 추가

- android/TodokTodok/app/build.gradle.kts
- android/TodokTodok/domain/build.gradle.kts
- android/TodokTodok/domain/src/main/java/com/example/domain/model/Book.kt
- android/TodokTodok/domain/src/main/java/com/example/domain/model/Comment.kt
- android/TodokTodok/domain/src/main/java/com/example/domain/model/DiscussionRoom.kt
- android/TodokTodok/domain/src/main/java/com/example/domain/model/Note.kt
- android/TodokTodok/domain/src/main/java/com/example/domain/model/User.kt
- android/TodokTodok/domain/src/main/java/com/example/domain/model/member/NickNameException.kt
- android/TodokTodok/domain/src/main/java/com/example/domain/model/member/Nickname.kt
- android/TodokTodok/domain/src/main/java/com/example/domain/model/member/User.kt
- android/TodokTodok/domain/src/test/java/com/example/domain/model/NicknameTest.kt
- android/TodokTodok/gradle/libs.versions.toml
- 모찌 & 동전 : 유저 도메인 모델 추가 및 도메인 모듈 테스트 환경 세팅
- 페토 : 댓글, 토론방, 기록 도메인 모델 추가
---
- 롸잇 나우 👍 
---
<br/>
<details>
- ❌ "성능이 안 좋다"
- ✅ "A 방법 대신 B를 사용하면 가독성이 향상될 것 같습니다"
- 토론을 하되, 리뷰를 넘길 때도 …
> #16 공통 도메인 모델 추가

- backend/src/main/java/todoktodok/backend/global/resolver/LoginMember.java
- backend/src/main/java/todoktodok/backend/global/resolver/MemberArgumentResolver.java
- Jwt Token에서 id 외에 추출해서 사용할 일이 없을 것이라고 판단해서 id Long 타입만 반환하도록 했습니다.
- close #21 
---
- 금일 중 빠른 시일 내에!
---
<br/>
<details>
- ❌ "성능이 안 좋다"
- ✅ "A 방법 대신 B를 사용하면 가독성이 향상될 것 같습니다"
- 토론을 …
> #21 ArgumentResolver 추가

- backend/src/main/java/todoktodok/backend/global/config/WebMvcConfig.java
- backend/src/main/java/todoktodok/backend/global/resolver/MemberArgumentResolver.java
- WebConfig에 ArgumentResolver 등록
- Authorization 헤더 추출 시 NPE 예외 처리 추가
---
- 오늘 최대한 빠르게~!
---
<br/>
<details>
- ❌ "성능이 안 좋다"
- ✅ "A 방법 대신 B를 사용하면 가독성이 향상될 것 같습니다"
- 토론을 하되, 리뷰를 넘길 때도 …
> #26 MemberArgumentResolver 로직 수정

- backend/src/main/java/todoktodok/backend/book/application/dto/response/BookResponse.java
- backend/src/main/java/todoktodok/backend/book/application/service/query/BookQueryService.java
- backend/src/main/java/todoktodok/backend/book/presentation/BookController.java
- backend/src/main/java/todoktodok/backend/shelf/domain/Shelf.java
- backend/src/main/java/todoktodok/backend/shelf/domain/repository/ShelfRepository.java
- backend/src/test/java/todoktodok/backend/DatabaseInitializer.java
- backend/src/test/java/todoktodok/backend/book/application/service/query/BookQueryServiceTest.java
- backend/src/test/java/todoktodok/backend/book/presentation/BookControllerTest.java
- backend/src/test/java/todoktodok/backend/member/presentation/fixture/MemberFixture.java
- close #25 
- 백엔드 컨벤션과 관련하여 몇 가지 논의되지 않은 부분들이 있어서 우선 임의로 작성했습니다.
혹시 논의나 수정이 필요한 부분이 있다면 말해주시면 적극 반영하겠습니다!
임의로 작성한 부분들 리스트는 아래와 같습니다.
- `Book` Entity -> `BookResponse` DTO 변환 시 DTO 내부에서 this 생성자 활용하여 변환
- `@Query` 작성 시 라인 컨벤션
- 모든 테스트에서 사용될 `MemberFixture` static 메서드 사용
- 추가로, 아직 Book, Shelf 도메인 관련하여 create 관련 기능이 존재하지 않아 테스트에서 회원과 동일하게 더미 데이터를 `DataInitializer`에 set 해두었습니다. 이 부분도 추후 create 관련 기능 추가 시 변경하는 게 좋을 것 같긴 합니다!
---
- 2025.07.20(일)에 확인해주셔야 Book이 필요한 곳에서 빠르게 사용할 수 있을 것 같습니다!
---
<br/>
<details>
- 피드백은 **코드, 프로세스, 사양만**을 …
> #25 내 서재 도서 전체 조회 API 추가

- backend/src/main/java/todoktodok/backend/book/domain/Book.java
- backend/src/main/java/todoktodok/backend/note/application/dto/request/NoteRequest.java
- backend/src/main/java/todoktodok/backend/note/application/dto/response/MyNoteResponse.java
- backend/src/main/java/todoktodok/backend/note/application/service/command/NoteCommandService.java
- backend/src/main/java/todoktodok/backend/note/application/service/query/NoteQueryService.java
- backend/src/main/java/todoktodok/backend/note/domain/Note.java
- backend/src/main/java/todoktodok/backend/note/domain/repository/NoteRepository.java
- backend/src/main/java/todoktodok/backend/note/presentation/NoteController.java
- backend/src/main/java/todoktodok/backend/shelf/domain/repository/ShelfRepository.java
- backend/src/test/java/todoktodok/backend/DatabaseInitializer.java
- backend/src/test/java/todoktodok/backend/note/application/service/command/NoteCommandServiceTest.java
- backend/src/test/java/todoktodok/backend/note/domain/NoteTest.java
- backend/src/test/java/todoktodok/backend/note/presentation/NoteControllerTest.java
Closes #29 
- 기록 생성 API 추가, 내기록 조회 API 추가
- 충돌 해결 : DataInitializer (기존 코드에 setNoteInfo 추가)
- ShelfRepository 메서드 추가
- 기록 생성 시 서재에 등록된 도서에 대한 기록인지 검증할 때 사용합니다.
- Book 도메인에 Builder 애노테이션 추가
---
- 오늘 안에 머지되면 좋겠어요! (최대한 빠르게)
---
<br/>
<details>
- **긍정적 …
> #29 기록 생성 및 내 기록 조회 기능 구현

- backend/src/main/java/todoktodok/backend/book/application/service/query/BookQueryService.java
- backend/src/main/java/todoktodok/backend/book/domain/repository/BookRepository.java
- backend/src/main/java/todoktodok/backend/book/presentation/BookController.java
- backend/src/test/java/todoktodok/backend/book/application/service/query/BookQueryServiceTest.java
- backend/src/test/java/todoktodok/backend/book/presentation/BookControllerTest.java
- backend/src/test/java/todoktodok/backend/member/presentation/fixture/MemberFixture.java
- close #22 
- 도서 검색 기능 구현입니다.
- book 도메인 패키지 내부만 변경사항 있어서 충돌 위험은 없을 것 같아요~!
---
- 변경사항이 크지 않아 빠르면 오늘, 늦어도 내일(7/21 월) 오전까지는 머지되면 좋겠습니다!
---
<br/>
<details>
- ❌ "성능이 안 좋다"
- ✅ "A 방법 …
> #22 도서 검색 기능 구현

- backend/src/main/java/todoktodok/backend/book/application/service/query/BookQueryService.java
- backend/src/main/java/todoktodok/backend/shelf/application/service/query/ShelfQueryService.java
- backend/src/main/java/todoktodok/backend/shelf/presentation/ShelfController.java
- backend/src/test/java/todoktodok/backend/book/application/service/query/BookQueryServiceTest.java
- backend/src/test/java/todoktodok/backend/shelf/application/service/query/ShelfQueryServiceTest.java
- backend/src/test/java/todoktodok/backend/shelf/presentation/ShelfControllerTest.java
- Close #43 
- 서재에 있는 도서를 조회해오는 것이기 때문에 명확하게 `/books/mine`에서 `/shelves`로 api 변경했습니다. 
---
- 7월 21일(월) 오후 6시 이전
- 백엔드 크루 논의 완료 후 수정 반영하는 것이기 때문에 최대한 빠르게 부탁드립니다~!
---
<br/>
<details>
- …
> #43 서재 도서 전체 조회 api 수정

- .github/workflows/backend-ci.yml
- backend/build.gradle
- backend/gradlew
- backend/gradlew.bat
- ci 잘 적용된 것 확인했숨니다
---
- 
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
- 주요 변경사항이나 새로운 …
> #60 백엔드 ci 추가

- backend/src/main/java/todoktodok/backend/comment/application/service/command/CommentCommandService.java
- backend/src/main/java/todoktodok/backend/comment/domain/Comment.java
- backend/src/main/java/todoktodok/backend/comment/domain/CommentReport.java
- backend/src/main/java/todoktodok/backend/comment/domain/repository/CommentReportRepository.java
- backend/src/main/java/todoktodok/backend/comment/presentation/CommentController.java
- backend/src/main/java/todoktodok/backend/discussion/domain/Discussion.java
- backend/src/main/java/todoktodok/backend/member/domain/Block.java
- backend/src/main/java/todoktodok/backend/member/domain/Member.java
- backend/src/main/java/todoktodok/backend/member/domain/MemberReport.java
- backend/src/test/java/todoktodok/backend/DatabaseInitializer.java
- backend/src/test/java/todoktodok/backend/comment/application/service/command/CommentCommandServiceTest.java
- backend/src/test/java/todoktodok/backend/comment/domain/CommentTest.java
- backend/src/test/java/todoktodok/backend/comment/domain/fixture/CommentFixture.java
- backend/src/test/java/todoktodok/backend/comment/presentation/CommentControllerTest.java
- backend/src/test/java/todoktodok/backend/discussion/domain/fixture/DiscussionFixture.java
- backend/src/test/java/todoktodok/backend/member/presentation/MemberControllerTest.java
- Close #65 
- 댓글 신고 기능 구현했습니다.
---
- 오늘 내로!
---
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
- 주요 …
> #65 댓글 신고 기능 구현

- backend/src/main/resources/application.yml
- backend/src/main/resources/data.sql
- backend/src/test/resources/application-test.yml
- 도서 초기 데이터 추가 및 설정 변경
---
- 테스트 배포를 위해 빠른 머지 부탁합니다!
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
- **PR은 최대 500 …
> #73 도서 초기 데이터 추가 및 설정 변경

- android/TodokTodok/app/src/main/AndroidManifest.xml
- android/TodokTodok/app/src/main/java/com/example/todoktodok/presentation/view/discussion/DiscussionFragment.kt
- android/TodokTodok/app/src/main/java/com/example/todoktodok/presentation/view/discussion/create/DiscussionRoomCreateActivity.kt
- android/TodokTodok/app/src/main/res/layout/activity_discussion_room_create.xml
- android/TodokTodok/app/src/main/res/values/dimen.xml
- android/TodokTodok/app/src/main/res/values/strings.xml
- closes #69 
- 토론방 생성 xml 구현
---
- today~* 부탁드립니다
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
- **PR은 최대 500 …
> #69 토론방 생성 xml 구현

- .github/workflows/backend-ci-cd-prod.yml
- .github/workflows/backend-ci.yml
- CI/CD 코드 수정
---
- 지금
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
- 주요 변경사항이나 새로운 패턴 …
> #75 CI/CD 코드 수정

- backend/src/main/java/todoktodok/backend/book/presentation/BookController.java
- backend/src/main/java/todoktodok/backend/comment/presentation/CommentController.java
- backend/src/main/java/todoktodok/backend/discussion/presentation/DiscussionController.java
- backend/src/main/java/todoktodok/backend/global/config/SwaggerConfig.java
- backend/src/main/java/todoktodok/backend/global/config/WebMvcConfig.java
- backend/src/main/java/todoktodok/backend/member/presentation/MemberController.java
- backend/src/main/java/todoktodok/backend/note/presentation/NoteController.java
- backend/src/main/java/todoktodok/backend/shelf/presentation/ShelfController.java
- Close #81 
- 스웨거 세팅!
---
- 오늘 내로!
---
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
- 주요 변경사항이나 …
> #81 Swagger 적용

- .github/workflows/android-ci.yaml
- android/TodokTodok/app/build.gradle.kts
- android/TodokTodok/app/src/main/AndroidManifest.xml
- android/TodokTodok/app/src/main/java/com/example/todoktodok/AppContainer.kt
- android/TodokTodok/app/src/main/java/com/example/todoktodok/data/di/DataSourceModule.kt
- android/TodokTodok/app/src/main/java/com/example/todoktodok/data/di/OkhttpModule.kt
- android/TodokTodok/app/src/main/java/com/example/todoktodok/data/di/RetrofitModule.kt
- android/TodokTodok/app/src/main/java/com/example/todoktodok/data/di/ServiceModule.kt
- android/TodokTodok/app/src/main/java/com/example/todoktodok/data/network/service/NoteService.kt
- android/TodokTodok/gradle.properties
- 네트워크 호출을 위한 Retrofit 기본 세팅 완료했습니다. 
- local.properties 파일에 다음과 같이 세팅하시면 됩니다 !
```
base_url = 서버 URL
```
- `serviceModule` 클래스에선 각각의 도메인 별로 서비스 인터페이스 파일을 만드시고 이곳에서 외부로 주입시키면 됩니다 !
---
- 2025.07.23.18:00
---
```
```
</details>
<br/>
<details>
<br>
작성자는 P5에 대해 아무런 의견을 달지 않고 무시해도 …
> #80 네트워크 연결 세팅

- backend/src/main/java/todoktodok/backend/comment/application/dto/CommentResponse.java
- backend/src/main/java/todoktodok/backend/comment/application/dto/response/CommentResponse.java
- backend/src/main/java/todoktodok/backend/comment/application/service/query/CommentQueryService.java
- backend/src/main/java/todoktodok/backend/comment/domain/repository/CommentRepository.java
- backend/src/main/java/todoktodok/backend/comment/presentation/CommentController.java
- backend/src/main/java/todoktodok/backend/member/application/dto/response/MemberResponse.java
- backend/src/test/java/todoktodok/backend/comment/application/service/query/CommentQueryServiceTest.java
- backend/src/test/java/todoktodok/backend/comment/presentation/CommentControllerTest.java
- Close #70 
- 토론방별 댓글 목록 구현했습니다.
- 일단 한꺼번에 보내주고, 무한 스크롤은 나중에 논의!
---
- 오늘 내로!
---
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
- 큰 작업은 여러 개의 작은 티켓으로 분할하여 …
> #70 토론방별 댓글 목록 조회 구현

- backend/src/main/java/todoktodok/backend/book/presentation/BookController.java
- backend/src/main/java/todoktodok/backend/member/presentation/MemberController.java
- backend/src/main/java/todoktodok/backend/note/application/service/query/NoteQueryService.java
- backend/src/main/java/todoktodok/backend/note/domain/repository/NoteRepository.java
- backend/src/main/java/todoktodok/backend/note/presentation/NoteController.java
- backend/src/test/java/todoktodok/backend/member/application/service/command/MemberCommandServiceTest.java
- backend/src/test/java/todoktodok/backend/note/application/service/command/NoteCommandServiceTest.java
- backend/src/test/java/todoktodok/backend/note/application/service/query/NoteQueryServiceTest.java
- backend/src/test/java/todoktodok/backend/note/domain/NoteTest.java
- backend/src/test/java/todoktodok/backend/note/presentation/NoteControllerTest.java
- 도서별 기록 조회 API 추가
- 기록 단일 조회 API 추가
---
- 내일까쥐
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
- **PR은 최대 500 Line …
> #50 기록 세부 조회 기능 구현

- backend/src/main/resources/data.sql
- 더미 데이터 추가
---
- 안드로이드 형님들이 필요하니까 바로
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
- 주요 …
> #104 더미 데이터 추가

- backend/src/main/java/todoktodok/backend/comment/presentation/CommentController.java
- backend/src/main/java/todoktodok/backend/discussion/presentation/DiscussionController.java
- backend/src/main/java/todoktodok/backend/member/presentation/MemberController.java
- backend/src/main/java/todoktodok/backend/note/presentation/NoteController.java
- backend/src/main/java/todoktodok/backend/shelf/presentation/ShelfController.java
- swagger parameter hidden 추가
---
- 바로~
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
- …
> #107 swagger parameter hidden 추가

- android/TodokTodok/app/src/main/java/com/team/todoktodok/data/network/request/DiscussionRequest.kt
- android/TodokTodok/app/src/main/java/com/team/todoktodok/data/repository/DefaultDiscussionRepository.kt
- android/TodokTodok/domain/src/main/java/com/team/domain/repository/DiscussionRepository.kt
토론방 제목과 의견이 반대로 생성되는 부분 수정
---
---
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
- 주요 …
> #143 토론방 생성 수정

- .github/workflows/issue-opened.yml
- .github/workflows/pr-closed-linked-close-issue.yml
- .github/workflows/pr-opened.yml
- Issue, PR 자동화
- close #144 
- 머지된 이후엔 `git pull origin main` 한번씩 해주세요!
---
- 빠르게 머지해주시면 자동화 빠르게 확인 가능합니닷
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
- 이슈 티켓 발행 시 이슈의 목표를 …
> #144 Issue, PR 자동화

- .github/workflows/pr-closed-linked-close-issue.yml
- pr closed linked close issue 스크립트에 오류가 있어 수정했습니다.
- 머지 완료 후 `git pull origin main` 한 번씩 해주십셔
---
- 바로바롯
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
- 이슈 티켓 발행 시 이슈의 목표를 …
> chore: pr closed linked close issue 스크립트 수정

- .github/workflows/pr-closed-linked-close-issue.yml
- backend/src/main/java/todoktodok/backend/discussion/application/dto/response/DiscussionResponse.java
- backend/src/test/java/todoktodok/backend/discussion/application/service/query/DiscussionQueryServiceTest.java
- backend/src/test/java/todoktodok/backend/discussion/presentation/DiscussionControllerTest.java
- close #153 
- 토론방 단일 조회 API 수정했습니다.
- @donghyun81 과 논의한 대로 response DTO 네이밍 수정하였고, 기록이 null인 경우 그대로 null 을 내려주도록 수정헀습니다.
- 변경사항에 대한 테스트 추가했습니다.
---
- 오늘(7월 28일) 내로~!
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details> …
> #153 토론방 단일 조회 API 수정

- backend/src/main/resources/data.sql
- close #164 
- ut용 더미데이터 수정
---
- 바로바로
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
- …
> #164 chore: ut용 init data 수정

- android/TodokTodok/app/src/main/java/com/team/todoktodok/data/network/service/BookService.kt
- android/TodokTodok/app/src/main/java/com/team/todoktodok/data/network/service/CommentService.kt
- android/TodokTodok/app/src/main/java/com/team/todoktodok/data/network/service/DiscussionService.kt
- android/TodokTodok/app/src/main/java/com/team/todoktodok/data/network/service/LibraryService.kt
- android/TodokTodok/app/src/main/java/com/team/todoktodok/data/network/service/MemberService.kt
- android/TodokTodok/app/src/main/java/com/team/todoktodok/data/network/service/NoteService.kt
- close #168 
- 백엔드에서 다음과 같이 동일한 도메인에 대한 API를 버저닝한다고 하셔서
저희도 이에 맞게 Base Url에서 버전 정보를 제외했습니다 :)
최대한 꼼꼼하게 확인해서 Service Interface에 버저닝 정보를 추가했는데 혹여 
실수한 부분 있으면 수정 부탁드려요 ㅎㅎ 
---
- 롸잇 나우 !
---
```
```
</details>
<br/>
<details>
<br>
</details> …
> #168 api versining으로 인한 base url 수정

- backend/src/main/java/todoktodok/backend/book/application/service/query/BookQueryService.java
- 알라딘 API로 도서 검색 시 isbn이 null이거나 없는 경우 수정
---
- 핫픽스 바로바로
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
- **PR은 최대 …
> #182 알라딘 API로 도서 검색 시 isbn이 null이거나 없는 경우 수정

- android/TodokTodok/app/src/main/java/com/team/todoktodok/data/network/response/discussion/DiscussionResponse.kt
- android/TodokTodok/app/src/main/java/com/team/todoktodok/presentation/utview/discussions/DiscussionsActivity.kt
- android/TodokTodok/app/src/main/java/com/team/todoktodok/presentation/utview/discussions/DiscussionsUiState.kt
- android/TodokTodok/app/src/main/java/com/team/todoktodok/presentation/utview/discussions/all/AllDiscussionFragment.kt
- android/TodokTodok/app/src/main/java/com/team/todoktodok/presentation/utview/discussions/my/MyDiscussionFragment.kt
- android/TodokTodok/app/src/main/java/com/team/todoktodok/presentation/utview/discussions/vm/DiscussionsViewModel.kt
- android/TodokTodok/domain/src/main/java/com/team/domain/model/Discussion.kt
- close #180 
- 토론방 -> 토론 생성 화면
- 토론방 -> 토론 상세 화면 이동 완료
---
- 다 같이 확인했으나 롸잇 나우 !
---
---
https://github.com/user-attachments/assets/3ac6119a-af56-406d-8b68-8a12fc755f65
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details> …
> #180 토론 목록 화면에서 토론 생성토론 단일 조회 화면 연결

- android/TodokTodok/app/src/main/java/com/team/todoktodok/data/core/PrettyJsonLogger.kt
- android/TodokTodok/app/src/main/java/com/team/todoktodok/data/di/OkhttpModule.kt
- 문쌤의 로깅 코드를 훔쳐와 적용했습니다 !
- 스크린샷 처럼 한 줄로 출력되던 Json 로그를 한 줄씩 출력하도록 했어요 !
---
- 2025.07.31 17:00
---
---
API 호출 후 로그켓 창에 NETWORK 입력해서 로그를 필터랑 하시면 편하게 확인하실 수 있습니다 !
--- 
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details> …
> #191 네트워크 json 응답 로깅 라이브러리 추가

- .coderabbit.yml
- 코드레빗이 Request Change시 저희가 머지할 수 없는 문제를 수정했어요 !
> #209 코드레빗 request change시 병합 불가 문제 해결

- .github/workflows/backend-ci-cd-dev.yml
- .github/workflows/backend-ci-cd-prod.yml
- close #227 
- 도커 이미지 태그 수정
---
- 지금
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
- 주요 …
> #227 도커 이미지 태그 수정

- .github/workflows/backend-ci-cd-dev.yml
- runner 재지정
---
- 
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
- 주요 변경사항이나 새로운 패턴 도입 …
> dev 배포 스크립트 수정

- .coderabbit.yml
> #266 토끼 진정제 투입(증분 리뷰 비활성화

- android/TodokTodok/app/src/main/java/com/team/todoktodok/data/datasource/member/DefaultMemberRemoteDataSource.kt
- android/TodokTodok/app/src/main/java/com/team/todoktodok/data/datasource/member/MemberRemoteDataSource.kt
- android/TodokTodok/app/src/main/java/com/team/todoktodok/data/network/service/MemberService.kt
- android/TodokTodok/app/src/main/java/com/team/todoktodok/data/repository/DefaultMemberRepository.kt
- android/TodokTodok/app/src/main/java/com/team/todoktodok/presentation/view/profile/activated/ActivatedBooksFragment.kt
- android/TodokTodok/app/src/main/java/com/team/todoktodok/presentation/view/profile/activated/vm/ActivatedBooksViewModel.kt
- android/TodokTodok/app/src/main/java/com/team/todoktodok/presentation/view/profile/activated/vm/ActivatedBooksViewModelFactory.kt
- android/TodokTodok/app/src/main/java/com/team/todoktodok/presentation/view/profile/adapter/ContentPagerAdapter.kt
- android/TodokTodok/app/src/test/java/com/team/todoktodok/presentation/vm/ActivatedBooksViewModelTest.kt
- android/TodokTodok/domain/src/main/java/com/team/domain/repository/MemberRepository.kt
- close #237 
- 프로필 화면의 활동 도서 가저오기 기능 구현 완료
---
- 2025.08.07 23:00
---
https://github.com/user-attachments/assets/0fd2fd45-1488-4034-a86e-45d791258c3d
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
<summary> 📖 효과적인 코드 …
> #237 내가 활동한 도서 api 연결

- .github/workflows/backend-ci-cd-prac.yml
- 프롬테일 세팅 오류 수정
---
- 
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
- 주요 변경사항이나 새로운 패턴 …
> #308 프롬테일 세팅 오류 수정1

- android/TodokTodok/app/src/main/java/com/team/todoktodok/data/datasource/reply/DefaultReplyRemoteDataSource.kt
- android/TodokTodok/app/src/main/java/com/team/todoktodok/data/datasource/reply/ReplyRemoteDataSource.kt
- android/TodokTodok/app/src/main/java/com/team/todoktodok/data/di/DataSourceModule.kt
- android/TodokTodok/app/src/main/java/com/team/todoktodok/data/di/RepositoryModule.kt
- android/TodokTodok/app/src/main/java/com/team/todoktodok/data/di/ServiceModule.kt
- android/TodokTodok/app/src/main/java/com/team/todoktodok/data/network/request/ReplyRequest.kt
- android/TodokTodok/app/src/main/java/com/team/todoktodok/data/network/response/comment/ReplyResponse.kt
- android/TodokTodok/app/src/main/java/com/team/todoktodok/data/network/service/ReplyService.kt
- android/TodokTodok/app/src/main/java/com/team/todoktodok/data/repository/DefaultReplyRepository.kt
- android/TodokTodok/domain/src/main/java/com/team/domain/model/Reply.kt
- android/TodokTodok/domain/src/main/java/com/team/domain/repository/ReplyRepository.kt
#333 
- 대댓글 API 연동
---
- 
---
API 연동만 하여서 스크린샷은 따로 없습니다!
---
-->
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
- …
> #333 대댓글 API 연동

- backend/src/main/java/todoktodok/backend/global/config/SwaggerConfig.java
- backend/src/main/java/todoktodok/backend/global/exception/GlobalExceptionHandler.java
- backend/src/main/java/todoktodok/backend/member/presentation/MemberController.java
- close #364 
- 스웨거 인증 설명 추가입니다.
- 추가하면서 몇 개 메서드 summary에 '회원별'이 들어가면 명확한 설명이 될 것 같아서 추가했습니다.
- ExceptionHandler에 .status 부분이 통일되어 있지 않아서 이 부분도 수정했고, 파라미터 라인 좀 정리했습니다.
- 스웨거 실행하면 아래와 같은 화면입니다~! 혹시 내용이 이해가지 않거나 수정해야될 부분 있으면 코멘트 남겨주세용!
---
- 오늘 중으로~
---
```
```
</details>
<br/>
<details>
<br>
작성자는 P4에 대해서는 아무런 의견을 달지 않고 무시해도 괜찮습니다. 해당 의견을 반영하는 게 좋을지 고민해 …
> #364 스웨거 인증 설명 추가

- backend/docker-compose.yml
- docker-compose.yml 수정
---
- 지금
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
- 주요 …
> #389 docker-compose.yml 수정

- backend/docker-compose.yml
- backend/src/main/java/todoktodok/backend/global/config/FlywayConfig.java
- backend/src/main/resources/application-dev.yml
- close #400 
- flyway 설정 추가
---
- 지금
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
- 주요 …
> #400 flyway 설정 추가

- .github/workflows/backend-ci-cd-dev.yml
- .github/workflows/backend-ci-cd-prac.yml
- 테스트임다
---
- 
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
- 주요 변경사항이나 새로운 패턴 도입 시 …
> chore: cd 스크립트 수정 테스트

- .github/workflows/backend-ci-cd-prac.yml
- 
---
- 
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details> …
> chore: cd 스크립트 수정 테스트 - 마지막임

- .github/workflows/backend-ci-cd-prac.yml
- 
---
- 
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details> …
> chore: cd 스크립트 수정 테스트 - ㄹㅇ마지막임

- .github/workflows/backend-ci-cd-prac.yml
- 
---
- 
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details> …
> chore: cd 스크립트 수정 테스트 - 찐막

- .github/workflows/backend-ci-cd-prac.yml
- backend/.gitignore
- 테스트입니닷
---
- 
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
- 주요 변경사항이나 새로운 패턴 도입 시 …
> chore: 로그 폴더 gitignore 추가 테스트

- .github/workflows/backend-ci-cd-prac.yml
- backend/config/docker-compose-dev.yml
- backend/config/promtail-config-dev.yml
- config 디렉토리 추가 테스트
---
- 
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
- 주요 변경사항이나 …
> chore: config 디렉토리 추가 테스트

- .github/workflows/backend-ci-cd-prac.yml
- clean log directory 추가
---
- 
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
- 주요 …
> chore: clean log directory 추가

- .github/workflows/backend-ci-cd-prac.yml
- backend/config/docker-compose-dev.yml
- promtail container name 수정
---
- 
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
- 주요 …
> chore: promtail container name 수정 테스트

- .github/workflows/backend-ci-cd-prac.yml
- backend/config/docker-compose-dev.yml
- 
---
- 
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details> …
> chore: 디렉토리 수정 테스트

- .github/workflows/backend-ci-cd-prac.yml
- 
---
- 
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details> …
> feat: 컨테이너 삭제하지 않고 중지만 하도록 테스트

- .github/workflows/backend-ci-cd-dev.yml
- .github/workflows/backend-ci-cd-prod.yml
- backend/config/docker-compose-dev.yml
- backend/config/docker-compose-prod.yml
- backend/config/promtail-config-dev.yml
- backend/config/promtail-config-prod.yml
- close #445 
- prod 서버 모니터링, 로깅 설정 추가입니다.
- prod 서버가 추가되면서 dev 관련 파일도 몇 가지 수정되었습니다.
- 기존에는 실행 중인 docker stop -> down -> start 로 진행했으나, 롤백을 고려하여 docker stop -> start로 수정했습니다.
(dev는 그대로 둘까 했으나 prod와 동일하게 맞추었습니다.)
- 충분히 practice 브랜치에서 연습했으나, prod 서버의 경우 제가 고려하지 못한 부분들이 있을 수도 있어서 cd가 성공할 거라고 장담하지 못하겠습니다🥹
- 모니터링 서버 `prometheus.yml`은 업데이트 후 ec2에서 pull 해둔 상태입니다. main까지 cd 잘 되면 모니터링 서버 도커 재실행하면 될 것 같습니다.
---
- 오늘 안에! (빠르게 dev->main까지도 갔으면 좋겠습니다)
---
```
```
</details>
<br/>
<details>
<br>
작성자는 P3에 대해 …
> #445 prod 서버 모니터링, 로깅 설정 추가

- .github/workflows/backend-ci-cd-dev.yml
- .github/workflows/backend-ci-cd-prod.yml
- backend/config/docker-compose-prod.yml
- close #476 
- 개발환경 : 기존 컨테이너 삭제 후 띄움
- 운영환경 -> 컨테이너 이름 동적 처리
- 24시간 사용하지 않은 이미지는 제거 하도록 스크립트 짜여져 있으므로 컨테이너 이름 동적 처리해도 크게 문제 없을 것으로 예상!
---
- fix이므로 바로 해주시면 dev 다시 올리겠슴다
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details> …
> #476 fix: docker 컨테이너 이름 충돌 수정

- backend/config/docker-compose-prod.yml
- docker 컨테이너 볼륨 마운트 경로 수정
- be -> dev -> main까지 갑니다
---
- ㅈㄱ ㅈㄱ
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
- …
> #483 fix: docker 컨테이너 볼륨 마운트 경로 수정

- android/TodokTodok/app/src/main/java/com/team/todoktodok/presentation/view/discussions/adapter/DiscussionViewHolder.kt
- android/TodokTodok/app/src/main/res/layout/item_discussion.xml
- 토론방 목록 사용자 프로필 원형으로
---
- 
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
- 주요 변경사항이나 …
> 토론방 목록 사용자 프로필 수정

- backend/src/main/java/todoktodok/backend/discussion/application/service/query/DiscussionQueryService.java
- backend/src/main/java/todoktodok/backend/discussion/domain/repository/DiscussionRepository.java
- backend/src/main/resources/db/local/schema.sql
- backend/src/test/java/todoktodok/backend/discussion/application/service/query/DiscussionQueryServiceTest.java
- Closes #541 
- 활성화된 토론방 조회 시 댓글 수가 올바르게 집계되지 않는 문제를 수정했습니다.
- 쿼리에서 DTO 생성자 인자 순서가 잘못 매핑되어 있던 부분을 수정했습니다.
- 댓글 수 집계 시, 대댓글 수를 포함하도록 로직을 수정했습니다.
- 로컬 개발 환경의 초기 스키마(`schema.sql`)에 `report` 테이블의 `reason` 컬럼을 추가했습니다.  
- dev/운영 DB에는 migration을 통해 이미 반영되어 있었으나, 로컬 초기 스키마에는 누락되어 있어 일관성을 맞췄습니다.
- 활성화된 토론방 조회 테스트를 보강했습니다.
- 첫 페이지, 중간 페이지, 마지막 페이지를 각각 독립적으로 검증하도록 수정했습니다.
- 복합 커서(`lastCommentedAt + discussionId`) 기반 페이지네이션을 고려하여,  
동일한 `lastCommentedAt` 값일 때 `discussionId` 내림차순으로 정렬되는지 확인하는 테스트를 추가했습니다.
- 커서 기반 페이지네이션에서 페이지 간 중복 항목이 발생하지 않음을 검증하는 테스트를 추가했습니다.
---
- 이번주 수요일까지 부탁드립니다!
---
```
```
</details>
<br/>
<details>
<br>
리뷰어는 PR의 내용이 서비스에 중대한 오류를 발생할 수 있는 가능성을 잠재하고 있는 등 중대한 코드 수정이 반드시 필요하다고 판단되는 경우, P1 태그를 통해 리뷰 요청자에게 수정을 요청합니다. 리뷰 요청자는 p1 …
> #541 활성화된 토론방 조회 시, 댓글 수가 제대로 조회되지 않는 문제 수정

- .github/workflows/backend-ci-cd-dev.yml
- .github/workflows/backend-ci-cd-prod.yml
- .github/workflows/backend-ci.yml
- an -> dev 머지 시 backend ci cd 돌아가고 있어서 backend cicd 스크립트 수정합니다.
- 경로를 backend 하위 변경사항이 있을 때만 cicd가 동작하도록 지정해두었어용
---
- 바로 보자마자!
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details> …
> #581 an -> dev 머지 시 backend ci cd 돌아가고 있어서 스크립트 수정

- backend/src/main/resources/application.yml
- close #663 
- firebase import 수정
---
- 바로!
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
- **PR은 최대 500 Line …
> #663 fix: firebase import 수정

- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-local.yml
- backend/src/main/resources/application-prod.yml
- backend/src/main/resources/application.yml
- backend/src/test/resources/application-test.yml
- 프로필별 액세스 토큰 시간 조정
- `git submodule update --remote` 필요
- 제일 처음 approve 하시는 백엔드 분 계시면 `git pull origin dev` 한 번 해주십셔
- close #690 
---
- 보면 바로
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
<summary> 📖 효과적인 코드 리뷰를 위한 …
> 프로필별 액세스 토큰 시간 조정

- backend/src/test/java/todoktodok/backend/discussion/application/service/query/DiscussionQueryServiceTest.java
- 토론방 조회 시 10분 이후 조회수 증가 / 10분 이전 조회수 미증가 테스트 수정했습니다.
- 해당 테스트는 Service 테스트이므로 생성 시 뷰 카운트 1이 적용되지 않습니다.
---
- 보면 바로!
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
- 이슈 티켓 발행 시 …
> test: 테스트 수정

- android/TodokTodok/app/build.gradle.kts
- android/TodokTodok/gradle/libs.versions.toml
- Slack에서 제공하는 compose lint 설정을 추가했어요 !
---
- 주말인 관계로 셀프머지!
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
- **PR은 …
> #720 Compose-lint dependency 추가

- backend/src/main/java/todoktodok/backend/discussion/application/dto/response/DiscussionResponse.java
- 토론방 조회 시 `lastCommentedAt` 필드를 응답에 추가합니다.
- 이유 : 현재 플레이스토어에서 메인화면에 오류가 나는 이유가 원래 활성화된 토론방 조회 시 lastCommentdAt 필드가 있었고 & 안드로이드에서 이를 받고 있었는데, 백엔드 측에서 lastCommentedAt 필드를 삭제하고 보내지 않게 되면서 안드로이드와 필드 불일치 에러가 난 것입니다.
- 이를 해결하기 위해 백엔드 측에서만 토론방 응답에 lastCommentedAt 필드를 임시로 추가했습니다. 어차피 안드로이드에서는 사용하지 않고 있기 때문에 fake 값을 보내고 있어요. 플레이스토어 심사 완료 후에 이는 제가 롤백해두겠습니다!
- 안드로이드는 자신이 지정한 필드만 받고, 그 외의 필드는 무시하기 때문에 안드로이드 변경사항은 없습니다.
- dev 잘되면 main까지 갑니다
‼️ api 명세가 바뀐다는 것은 클라이언트와 서버의 규약이 바뀌는 것이기 때문에, 양측의 합의가 필요해요.
응답에 필드를 추가하는 것은 클라이언트에 영향이 없지만, 필드를 빼면 클라이언트도 코드를 수정해야 하기 때문에 항상 안드로이드와 합의 및 변경 후 공지해주기 바랍니다!! :+1:
---
- 보자마자
---
```
```
</details>
<br/>
<details>
<br>
리뷰어는 PR의 내용이 서비스에 중대한 오류를 발생할 수 있는 가능성을 잠재하고 있는 등 중대한 코드 수정이 반드시 필요하다고 판단되는 경우, P1 태그를 통해 리뷰 …
> #736 토론방 조회 시 응답 필드 추가

- android/TodokTodok/app/src/main/AndroidManifest.xml
- android/TodokTodok/app/src/main/java/com/team/todoktodok/presentation/xml/book/SelectBookActivity.kt
- android/TodokTodok/app/src/main/java/com/team/todoktodok/presentation/xml/book/vm/SelectBookViewModel.kt
- android/TodokTodok/app/src/main/java/com/team/todoktodok/presentation/xml/discussion/create/CreateDiscussionRoomActivity.kt
- android/TodokTodok/app/src/main/res/drawable/bg_gray_ed_radius_16dp.xml
- android/TodokTodok/app/src/main/res/drawable/bg_radius_16dp.xml
- android/TodokTodok/app/src/main/res/layout/activity_create_discussion_room.xml
- android/TodokTodok/app/src/main/res/values/colors.xml
- android/TodokTodok/app/src/main/res/values/strings.xml
- closed #760
- 토론방 생성 화면 디자인 변경했습니다
---
- 2025.10.06 토론방 생성 화면 변경
---
---
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
- 큰 작업은 여러 개의 작은 티켓으로 …
> #760 토론방 생성 화면 변경 

- android/TodokTodok/app/src/main/java/com/team/todoktodok/presentation/compose/main/MainScreen.kt
- android/TodokTodok/app/src/main/java/com/team/todoktodok/presentation/compose/main/vm/MainViewModel.kt
- android/TodokTodok/app/src/main/res/values/strings.xml
- 뒤로가기 두 번 스와이프시 앱 종료 기능을 추가했습니다
---
- 명절 기념 셀프 머지
---
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details>
- **PR은 최대 …
> #757 뒤로가기 두 번으로 앱 종료 기능 추가

- backend/src/main/resources/application-performance.yml
- 
---
- 
---
```
```
</details>
<br/>
<details>
<br>
</details>
<br/>
<details> …
> chore: application-performance.yml의 flyway 경로 추가
